AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
Layout/LineLength:
  Max: 100
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true