addons:
  postgresql: 9.6
before_install:
  - gem install -v 1.17.2 bundler
  - gem install -v 13.0.1 rake
after_success:
  - bundle exec coveralls push
language: ruby
dist: trusty
rvm:
  - 2.5
  - 2.6
script:
  - bundle -v
  - rake db:setup RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop -a -x