addons:
  postgresql: 9.6
before_install:
  - gem install bundler
after_success:
  - bundle exec coveralls push
language: ruby
dist: trusty
rvm:
  - 2.5
  - 2.6
script:
  - bundle -v
  - rake db:setup RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop -a -x