addons:
  postgresql: 9.6
language: ruby
before_install:
  - gem install bundler
dist: trusty
rvm:
  - 2.5
  - 2.6
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop -a -x