addons:
  postgresql: 9.6
language: ruby
dist: trusty
rvm:
  - 2.5
  - 2.6
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - rake db:setup RAILS_ENV=test
  - rspec
  - bundle exec rubocop -a -x