addons:
  postgresql: 9.6
before_install:
  - gem install bundler
language: ruby
dist: trusty
rvm:
  - 2.5
  - 2.6
script:
  - rake db:setup RAILS_ENV=test
  - bundle exec coveralls push 
  - bundle exec rubocop -a -x