development:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: starbus_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: starbus_test
  pool: 5
  username: postgres
  password: postgres

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
